# Generated by Django 4.2 on 2024-09-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_course_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.CharField(max_length=255),
        ),
    ]
