# Generated by Django 4.2 on 2024-09-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='passed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
