# Generated by Django 4.2 on 2024-09-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='withdrawn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
