# Generated by Django 4.2 on 2024-09-23 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_email_alter_student_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
