# Generated by Django 4.2 on 2024-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emaillist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
                ('purge', models.BooleanField(default=False)),
            ],
        ),
    ]
