# Generated by Django 4.2 on 2024-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emaillist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
                ('purge', models.BooleanField(default=False)),
            ],
        ),
    ]
