# Generated by Django 4.2 on 2024-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_enrollment',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_enrollment',
            field=models.BigIntegerField(default=0),
        ),
    ]
