# Generated by Django 4.2 on 2024-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
